# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: pages

# Makes workflow run on push to the main branch.
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug:
        default: false
        description: Use Tmate session for debugging
        type: boolean

env:
  NPM_CONFIG_CACHE: "${{ github.workspace }}/.cache/npm"
  NPM_CONFIG_STORE_DIR: "${{ github.workspace }}/.cache/pnpm/store"

jobs:
  docs:
    name: Build and publish website
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: |
            .cache
            node_modules
          key: >-
            node-22_${{ runner.os }}_pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install Just
        run: >-
          curl -LSfs https://just.systems/install.sh | bash -s -- --to
          /usr/local/bin
      - name: Install Node interpreter
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install development dependencies
        run: just setup
      - name: Build website
        run: just build
      - name: Publish website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: dist
      - name: Setup Tmate session if debug enabled
        if: >-
          ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
